name: resto_app
description: "Dicoding Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.10
  google_fonts: ^6.2.1
  http: ^1.3.0
  lottie: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    # fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
